#pragma once

#define TO_UINT16 static_cast<unsigned short>

// request level -> give's context -> play!

enum sv2cl_t
{
	SV2CL_WELCOME,
	SV2CL_INTRODUCE_CHARACTER,
	SV2CL_NEXT_LEVEL_ALLOW,
	SV2CL_COMMANDS,
};

enum cl2sv_t
{
	CL2SV_MY_CHARACTER,
	CL2SV_REQUEST_NEXT_LEVEL,
	CL2SV_COMMANDS
};

/*
enum shot_type_t
{
	SHOT_TYPE_EFF_FOG,
	SHOT_TYPE_EFF_HOUSE,
	SHOT_TYPE_EFF_LAST_MESSAGE,
	SHOT_TYPE_EFF_MESSAGE,
	SHOT_TYPE_EFF_PIECE,
	SHOT_TYPE_EFF_WARNING_MESSAGE,
	SHOT_TYPE_AP_MISSILE,
	SHOT_TYPE_BOMB,
	SHOT_TYPE_FIRE,
	SHOT_TYPE_GREMADE,
	SHOT_TYPE_GUN,
};
*/